name: Pull Request Checks

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]


jobs:

  build:

    runs-on: ubuntu-22.04

    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Execute unit tests
      run: dotnet test

    - name: Create NuGet Package
      env:
        Version: 0.${{ github.run_number }}.${{ github.run_attempt }}-alpha
      run: dotnet pack -p:PackageVersion=$Version --include-source
