name: Publish New Release

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: write


jobs:

  build:
    runs-on: ubuntu-22.04
    env:
      Version: 0.${{ github.run_number }}.${{ github.run_attempt }}-alpha

    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

#    - name: Execute unit tests
#      run: dotnet test

#    - name: Create NuGet Packages
#      run: dotnet pack -p:PackageVersion=$Version

#    - name: Push Packages to NuGet
#      env:
#        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
#      run: dotnet nuget push "**/*.nupkg" -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json

    - name: Create tag
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: 'refs/tags/${{Version}}',
            sha: context.sha
          })
