name: Pull Request Checks

on:
  pull_request:
    branches: [ "develop", "release" ]


jobs:

  check-formatting:
    runs-on: ubuntu-22.04
    steps:
      - name: Format
        run: dotnet format --verify-no-changes --verbosity diagnostic

  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json
      - name: Execute unit tests
        run: dotnet test /warnaserror
