name: Pull Request Checks

on:
  pull_request:
    branches: [ "develop", "release" ]


jobs:

  test:

    runs-on: ubuntu-22.04


    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: global.json

    - name: Execute unit tests
      run: dotnet test
