name: Pull Request Checks

on:
  pull_request:
    branches: [ "main" ]


jobs:

  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json
      - run: dotnet format --verify-no-changes --verbosity diagnostic
      - run: dotnet test /warnaserror
